### ISSUE TITLE
Refactor packages and codebase

### ISSUE THREAD

**Issue by qhng** [CS2103AUG2016-T14-C2/main#45]

**Comment by e0003801** [comment]
What package?

**Comment by qhng** [comment]
Settled already. Wait for merge.

**Comment by e0003801** [comment]
Refactor Task class to fall under model.task package?

**Comment by qhng** [comment]
All the codes. Including removing unused classes. I have a pending merge.

**Comment by e0003801** [comment]
May want to take a look at AddCommand. Should move new Task() from ctor to execute() for consistency.

**Comment by qhng** [comment]
Okay. Will do in #72

**Comment by qhng** [comment]
Closed. See #71
