### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2016-T14-C2/main#52]
## User stories
- You need a user story to change the location of the storage file
## Use cases
- Your use cases are nice and detailed :+1: 
- You have formatting issues with the extensions. please fix them
## NFR
- you have a good set of NFRs.
## Products survey
- may be you need to spend some time with each of the product you mentioned to identify their weaknesses as required by Jim!
- we generally expect at least one product surveyed per person ;-)

Remove {More to be added} if there is nothing more to add :-P

**Comment by qhng** [comment]
Superseded by #57, #58, #59, #60.
