### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2016-T14-C2/main#73]
## Developer guide
- **Architecture**
  - Are you planning to use the same architecture as AddressBook? If there are changes, pleas updated it to reflect the architecture of your product.
- **Sequence diagram**
  - Consider adding a sequence diagram for add/edit command since it gives a better idea how to write complex sequence diagrams
- Update _UI Component_, _Model component_ and _Storage component_ sections to reflect your product design.
- **Testing**
  - Do you still use `UrlUtilTest` if I remember right you don't use the browser panel, right?
- **User stories**
  - Need a user story to relocate the storage file!
- **Use cases**
  - I looked at only the first one. Quite well thought of extensions :+1: 
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
  - Similarly, you can explain other interesting design decisions you made.
## User guide
- Please change the screenshots to reflect your product
- In the table under `add`, please link to `DATE` section, where you say "see DATE", that will be helpful.
- Under `modify`, it may be more appropriate to say "similar to Adding a task" rather than "see Adding a task".
- :+1: for a detailed user guide! I like it :-)
- You can add a few more screenshots; where applicable, consider using partial screenshots so that if you change something in other parts of the UI, you don't need to update all screenshots.
- You don't have a command to change the storage location; this is one of the must-have features!
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

**Comment by qhng** [comment]
Superseded. See #85 #86
