### ISSUE TITLE
[DevGuide] Update DeveloperGuide.md

### ISSUE THREAD

**Issue by qhng** [CS2103AUG2016-T14-C2/main#86]
## Developer guide

Fixed Issues
- **Architecture**
  - Are you planning to use the same architecture as AddressBook? If there are changes, please update it to reflect the architecture of your product.
- **Sequence diagram**
- Update _UI Component_, _Model component_ and _Storage component_ sections to reflect your product design.
- **User stories**
  - Need a user story to relocate the storage file!

Unfixed Issues
- **Sequence diagram**
  - Consider adding a sequence diagram for add/edit command since it gives a better idea how to write complex sequence diagrams
- **Testing**
  - Do you still use `UrlUtilTest` if I remember right you don't use the browser panel, right?
- **Use cases**
  - I looked at only the first one. Quite well thought of extensions :+1: 
- Suggested additions:
  - **Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.**
  - Similarly, you can explain other interesting design decisions you made.

**Comment by qhng** [comment]
Also see #60 #59 #57

**Comment by e0003801** [comment]
> Architecture
> Are you planning to use the same architecture as AddressBook? If there are changes, please update it to reflect the architecture of your product.

Fixed by 9f44ee6ad56ad041906e865be6177b1f57d66fe7
